name: "Prod Pipeline"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: "prod"
      aws-assume-role-arn: "arn:aws:iam::809659887572:role/github-actions-gmenegatto"
      aws-statefile-s3-bucket: "gmenegatto-us-east-1-terraform-state-file"
      aws-lock-dynamodb-table: "gmenegatto-us-east-1-terraform-lock"
      aws-region: "us-east-1"
